---
title: "Brainstorming for generals exam"
description: |
  The more I learn the less I know
author:
  - name: Jessica
categories:
  - research
date: 10-29-2025
output:
  distill::distill_article:
    self_contained: false
---

I'm in my fourth year of my PhD program, and I am starting to think about what topics I want to cover for my generals exam. After 3 years of work, I've come up with 3 different areas that I'm interested in. Broadly, I'm interested in thinking critically about how we measure latent variables. How do we know that we're measuring and estimating something properly that we can't observe in real life?  

### Estimation issues in latent class models
This is the first topic that I thought to do, especially since my master's work concentrates on it. Originally I wanted to write a literature review purely focusing on estimation issues in mixture models, but I ran into an issue. If I want to dig deep on estimation I would have to spend time reading theoretical papers describing the geometry and properties of the likelihood surface, as well as theoretical properties about estimation algorithms. I tried to do some initial readings on the geometry of the surface of the likelihood surface, and I just got really lost. I feel that my strengths are in empirical data and focusing on how researchers fit latent class models in real life, rather than theoretical principles of what the likelihood surface hypothetically looks like. 

I'm mainly interested in local solutions - can their presence, frequency, or location give us any insight about the quality of our solution? Can we examine and even accept a local solution despite its inferior LL value if it aligns better with our theory? Recommendations for class enumeration mention the importance of considering the theoretical relevance of the additional class estimated, which can be the driving factor in ultimately settling on a K class solution. This decision is not based on any computed value; if that is the case, then why can't we also explore suboptimal likelihood solutions that align better with our theory? There are less papers on this topic, most of which I included in my master's thesis. That is why I've been thinking of other topics to cover in my generals exam. 


### Discrete vs Continous Latent Variable Models
This is a topic that I only got immersed in 2 weeks ago, but I think it is incredibly important and is understudied. Since I've learned about all these latent variable models the concept of choosing a "side" of viewing the latent variable as discrete or continuous has been mind-boggling to me. How do we know how to conceptualize something that we cannot actually see with our eyes? I read many applied papers where people just fit a latent class model, or just fit an IRT model, without discussion of why they didn't consider the other model. It seems that many just pick an inherent side, maybe following what others in their field normally pick, and do analysis following that framework. 

My advisor recently mentioned a paper by [Markon and Krueger (2006)](https://pubmed.ncbi.nlm.nih.gov/16953702/) that uses information criterion (BIC, AIC, etc.) as a metric to determine whether continuous or discrete latent variables are more appropriate given the data. This was incredibly intriguing to me as I was only familiar with using BIC in terms of choosing the best number of classes in LCA. They found that BIC was a good indication of identifying whether the data were generated assuming a discrete or latent variable, given sufficient sample size. From my understanding of the paper, I don't think they actually generated discrete data. Rather, they treated the discrete variables as just chopped up, fewer-in-quantity versions of a continuous latent variable.. in that case I don't think LCA models have a fair fight, if they are just continuous latent variable models but with reduced-information... 

BIC also penalizes for complexity and too many parameters. LCA will almost always have more parameters to be estimated than a factor model or IRT model, so it also seems unfair. Another interesting question is whether we should be looking for parsimony, which we are by using BIC, if our goal is to model population heterogeneity. Maybe it is interesting to have a small class of 100 people that exhibit some qualitatively different pattern of responses, even if it overparameterizes the model and creates a higher BIC...

My advisor brought up something that I really want to explore. These comparisons of discrete vs continous latent variable models using information criteria oftentimes use items that were originally developed using factor analysis or IRT, which are continuous latent variable models. If the items have been curated and modified within the framework that assumes the latent variable is continous, then it's probably not surprising that these models would be superior. Now I really want to look for data and items that were developed with a discrete variable framework. I think the DSM follows this framework, as it takes a categorical approach in describing mental disorders and does not assume the disorders to be dimensional.

Another paper that I read recently by [Wu et. al (2011)](https://www.sciencedirect.com/science/article/pii/S037687161100144X?via%3Dihub) conducts an empirical investigation of IRT vs LCA by fitting both models to data of poly-substance use disorders (SUD) in a sample of opioid-dependent patients. They found that a 2 class LCA model fit the data better than 1PL or 2PL IRT models in terms of BIC. The 2 class model separated 10% of individuals in the sample who had high poly-SUDs in all substances including amphetamine and sedatives, while 90% of the sample had high poly-SUDs in all substances besides those two. Individuals in the smaller class were more likely to have greater psychiatric problems. Item parameter estimates on the other hand found that individuals who responded to having amphetamine or sedative dependence were higher in SUD severity compared to those that didn't. In this case these two models told similar stories. I wonder if it would be a good idea for more applied researchers to try both IRT and LCA for their data rather than just choosing one.

I'm interested in exploring further how researchers have grappled with these two different frameworks and how they evaluate which one to go with. Are there other values besides information criteria that we can use? If we'll never know the truth because we don't know whether our empirical data come from a discrete latent variable data generating process or continuous, does it matter? One argument I've seen is that we should favor whatever model is useful or practical. Whichever model is better at identifying individuals that need treatment, or identifying individuals with poor outcomes on a construct, with "better" depending on the construct, we should use. But then, if we're only interested in prediction, shouldn't we just use machine learning? If we focus too much on utility we're ignoring the fundamental question in psychological research of understanding the underlying mechanisms. 

I'm clearly still wrestling with these ideas... and I'm looking forward to reading more papers.

### Barriers to receiving mental health support

This is the last topic I'll mention today. I've been domain-less these past 3 years, mainly focusing on models and algorithms. I've found that using a domain as an example to anchor my thinking as I'm pondering about important questions like discrete vs continuous or how to choose a final latent class solution has been immensely helpful. For my master's thesis I've focused only on simulated data, but in order to better prepare myself for a career post-grad where I will most likely be working with empirical data, I have decided to focus my efforts on gaining experience analyzing real data. Since I work at UCSF I have access to student mental health data. A set of items that I've come across are binary items related to different potential barriers to getting mental health support such as stigma, lack of knowledge, or financial constraints. To me, these items are potentially a good example of items that were developed with the idea that the latent variable, barriers, is discrete. There are papers I've seen that have developed a multi-dimensional scale for measuring barriers, but I have also seen barriers being thought of as discrete - with various individuals having different combinations of barriers. Most of this is my own hypotheses and musings that are not backed up with any analysis, so take everything with a grain of salt. 

These are the ideas that have been consuming me (in a good way), and I'm super excited to refine them and learn more in these next few months. 

Thanks for reading. 


